# externalIP: 
externalIP:
# Volume Settings
nfs:
  enabled: false
  storageClassName: astrago-nfs-csi
  server:
  basePath:
local:
  enabled: false
  storageClassName: astrago-local-storage
  nodeName:
  basePath:
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    repository: "xiilab/astrago"
    imageTag: "core-v1.0.7"
  batch:
    repository: "xiilab/astrago"
    imageTag: "batch-v1.0.7"
  monitor:
    repository: "xiilab/astrago"
    imageTag: "monitor-v1.0.7"
  frontend:
    repository: "xiilab/astrago"
    imageTag: frontend-seoultech-74c4
